export const COLORS = {
  background: '#FDF8F3',
  primary: '#FB7F6E', // Slightly softer coral
  secondary: '#14B8A6', // Modern teal (harmonized with banner colors)
  text: '#334155', // Softer, more contemporary gray
  stations: {
    purple: { bg: '#B39DDB', light: '#E1D5F0' },
    yellow: { bg: '#FFE082', light: '#FFF3C4' },
    blue: { bg: '#81D4FA', light: '#D0EFFF' },
    green: { bg: '#A5D6A7', light: '#D7F0D8' },
    pink: { bg: '#F8BBD9', light: '#FDE4F0' },
  },
};

export const DEFAULT_TEACHER_NAMES = {
  purple: 'Ms. Angie',
  yellow: 'Ms. Maggie',
  blue: 'Mrs. Childress',
  green: 'Mr. Michael',
  pink: 'Ms. Sonya',
};

export const DEFAULT_STUDENTS = [
  { id: 1, name: 'Emma', group: 'purple', photo: null },
  { id: 2, name: 'Liam', group: 'purple', photo: null },
  { id: 3, name: 'Olivia', group: 'yellow', photo: null },
  { id: 4, name: 'Noah', group: 'yellow', photo: null },
  { id: 5, name: 'Ava', group: 'blue', photo: null },
  { id: 6, name: 'Elijah', group: 'blue', photo: null },
  { id: 7, name: 'Sophia', group: 'green', photo: null },
  { id: 8, name: 'James', group: 'green', photo: null },
  { id: 9, name: 'Isabella', group: 'pink', photo: null },
  { id: 10, name: 'William', group: 'pink', photo: null },
];

export const DEFAULT_ROTATION_ORDER = ['purple', 'yellow', 'blue', 'green', 'pink'];

export const DEFAULT_STATION_CONFIG = {
  yellow: { top: 12, left: 40, width: 100, height: 65 },
  blue: { top: 12, left: 155, width: 100, height: 65 },
  green: { top: 12, left: 270, width: 100, height: 65 },
  purple: { top: 110, left: 12, width: 75, height: 115 },
  pink: { top: 210, left: 155, width: 110, height: 65 },
};

export const EMOJI_OPTIONS = [
  '📺',
  '🚪',
  '📚',
  '🎨',
  '🧸',
  '🪑',
  '🗄️',
  '🖥️',
  '📦',
  '🎵',
  '🧩',
  '✏️',
  '📐',
  '🗑️',
  '🚿',
  '🪴',
  '🛋️',
  '🎤',
  '🎧',
  '🔬',
  '🧪',
  '🌍',
  '🗂️',
  '📎',
  '🖍️',
  '🖊️',
  '📏',
  '🧲',
  '🎲',
  '🪣',
  '🧽',
  '🪞',
  '💡',
  '🔔',
  '📌',
  '🏠',
  '🚰',
  '🧳',
  '📖',
  '🎭',
  '🎪',
  '🪁',
  '🛒',
  '🧊',
  '☂️',
  '🪜',
  '🖼️',
  '📮',
];

export const STATION_COLOR_OPTIONS = [
  { label: 'Purple', bg: '#B39DDB', light: '#E1D5F0' },
  { label: 'Yellow', bg: '#FFE082', light: '#FFF3C4' },
  { label: 'Blue', bg: '#81D4FA', light: '#D0EFFF' },
  { label: 'Green', bg: '#A5D6A7', light: '#D7F0D8' },
  { label: 'Pink', bg: '#F8BBD9', light: '#FDE4F0' },
  { label: 'Red', bg: '#EF9A9A', light: '#FFCDD2' },
  { label: 'Orange', bg: '#FFCC80', light: '#FFE0B2' },
  { label: 'Teal', bg: '#80CBC4', light: '#B2DFDB' },
  { label: 'Indigo', bg: '#9FA8DA', light: '#C5CAE9' },
  { label: 'Brown', bg: '#BCAAA4', light: '#D7CCC8' },
  { label: 'White', bg: '#E0E0E0', light: '#FFFFFF' },
];

export const DEFAULT_STATION_COLORS = {
  purple: { bg: '#B39DDB', light: '#E1D5F0' },
  yellow: { bg: '#FFE082', light: '#FFF3C4' },
  blue: { bg: '#81D4FA', light: '#D0EFFF' },
  green: { bg: '#A5D6A7', light: '#D7F0D8' },
  pink: { bg: '#F8BBD9', light: '#FDE4F0' },
};

export const STUDENT_EMOJI_OPTIONS = [
  // Animals
  '🐉',
  '🦄',
  '🐱',
  '🐶',
  '🐸',
  '🦊',
  '🐼',
  '🐨',
  '🦁',
  '🐯',
  '🐻',
  '🐰',
  '🐙',
  '🦋',
  '🐢',
  '🦈',
  '🐬',
  '🦅',
  '🦉',
  '🐝',
  '🐞',
  '🦖',
  '🐳',
  '🦩',
  '🐧',
  '🐥',
  '🦜',
  '🐠',
  '🦔',
  '🐺',
  // Fun & Sports
  '🌟',
  '🚀',
  '🎨',
  '🎮',
  '🏀',
  '⚽',
  '🎸',
  '👑',
  '💎',
  '🌈',
  '🦸',
  '🧙',
  '🎯',
  '🛹',
  '🏄',
  '🎪',
  '🎠',
  '🧁',
  '🍦',
  '🌻',
  '🌸',
  '🔮',
  '🎈',
  '🪐',
  '⚡',
  '🌊',
  '❄️',
  '🍄',
  '🎵',
  '💫',
  // More Animals
  '🐮',
  '🐷',
  '🐹',
  '🐲',
  '🦕',
  '🦎',
  '🐊',
  '🦀',
  '🐡',
  '🦑',
  '🐌',
  '🐛',
  '🦗',
  '🕷️',
  '🦂',
  '🦧',
  '🐫',
  '🦒',
  '🦘',
  '🦡',
  '🐿️',
  '🦃',
  '🦚',
  '🦢',
  '🦨',
  '🐓',
  '🦤',
  '🪿',
  '🐇',
  '🦙',
  // Food & Nature
  '🍕',
  '🌮',
  '🍔',
  '🍟',
  '🍩',
  '🧁',
  '🍪',
  '🍭',
  '🍬',
  '🧃',
  '🥤',
  '🍉',
  '🍓',
  '🫐',
  '🥑',
  '🌺',
  '🌴',
  '🍀',
  '🌵',
  '🌲',
  '🍁',
  '🪻',
  '🌷',
  '💐',
  '🪷',
  '☘️',
  '🌾',
  '🫧',
  '🪸',
  '🌙',
  // Objects & Activities
  '🎭',
  '🎬',
  '📚',
  '🔭',
  '🧪',
  '🎹',
  '🥁',
  '🪘',
  '🏆',
  '🥇',
  '🎳',
  '🏓',
  '🛼',
  '🎿',
  '🏊',
  '🧲',
  '🪁',
  '🎲',
  '🧩',
  '🪀',
  '🤖',
  '👾',
  '🛸',
  '🌋',
  '🏰',
  '⛵',
  '🚂',
  '🎡',
  '🎢',
  '🎠',
];

export const TOKEN_EMOJI_OPTIONS = [
  '⭐',
  '🌟',
  '💎',
  '🔥',
  '❤️',
  '🍀',
  '🎯',
  '🏅',
  '👑',
  '🦄',
  '🐾',
  '🌈',
  '🍎',
  '🎵',
  '🚀',
  '💜',
  '🏆',
  '🎖️',
  '💪',
  '🧡',
  '💚',
  '💙',
  '🩷',
  '✨',
  '🪙',
  '💰',
  '🎁',
  '🎀',
  '🌺',
  '🍩',
  '🧸',
  '⚡',
];

export const BANNER_COLORS = [
  '#14B8A6', // Softer teal
  '#3B82F6', // Modern blue
  '#A78BFA', // Softer purple
  '#F472B6', // Softer pink
  '#F87171', // Softer red
  '#FBBF24', // Warm amber
  '#34D399', // Softer emerald
  '#818CF8', // Softer indigo
  '#64748B', // Contemporary slate (replaces dark navy)
];
