// Widget metadata: labels, icons, minimum grid sizes, and default add position
const widgetRegistry = {
  banner: {
    label: 'Banner',
    icon: '🏷️',
    minW: 4,
    minH: 2,
    defaultW: 12,
    defaultH: 2,
  },
  floorplan: {
    label: 'Floor Plan',
    icon: '🗺️',
    minW: 4,
    minH: 6,
    defaultW: 7,
    defaultH: 14,
  },
  timerPanel: {
    label: 'Timer & Controls',
    icon: '⏱️',
    minW: 3,
    minH: 5,
    defaultW: 5,
    defaultH: 8,
  },
  tokenBoard: {
    label: 'Token Board',
    icon: '🎯',
    minW: 3,
    minH: 2,
    defaultW: 5,
    defaultH: 2,
  },
  voiceLevel: {
    label: 'Voice Level',
    icon: '🔈',
    minW: 3,
    minH: 2,
    defaultW: 5,
    defaultH: 2,
  },
  firstThen: {
    label: 'First/Then',
    icon: '➡️',
    minW: 3,
    minH: 2,
    defaultW: 5,
    defaultH: 2,
  },
  stationGroups: {
    label: 'Groups',
    icon: '👥',
    minW: 3,
    minH: 3,
    defaultW: 5,
    defaultH: 4,
  },
  countdown: {
    label: 'Countdown',
    icon: '⏰',
    minW: 3,
    minH: 2,
    defaultW: 5,
    defaultH: 2,
  },
  quickMessage: {
    label: 'Message',
    icon: '📋',
    minW: 3,
    minH: 2,
    defaultW: 5,
    defaultH: 2,
  },
  starPoints: {
    label: 'Class Stars',
    icon: '⭐',
    minW: 3,
    minH: 3,
    defaultW: 5,
    defaultH: 3,
  },
  clock: {
    label: 'Clock',
    icon: '🕐',
    minW: 2,
    minH: 1,
    defaultW: 5,
    defaultH: 1,
  },
};

export default widgetRegistry;
